name: dotnet format

on:
  push:
    paths:
      - '**'

jobs:
  check-format:
    runs-on: windows-latest

    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install dotnet-format tool
        run: dotnet tool update -g dotnet-format

      - name: Check out code
        uses: actions/checkout@v3

      - name: Run dotnet format
        run: dotnet-format --folder --check --verbosity diagnostic