name: Run Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore src/PepeProject.sln
      
    - name: Build solution
      run: dotnet build src/PepeProject.sln --no-restore --configuration Release
      
    - name: Run tests
      run: dotnet test src/PepeProject.sln --no-build --verbosity normal --configuration Release