name: .NET Core CI and Format Check

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-format:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore src/PepeProject.sln

    - name: Build
      run: dotnet build src/PepeProject.sln --configuration Release --no-restore

    - name: Install dotnet-format
      run: dotnet tool update -g dotnet-format

    - name: Check code formatting
      run: dotnet format src/PepeProject.sln --verify-no-changes --verbosity detailed