name: dotnet format

on:
  push:
    paths:
      - '**'

jobs:
  check-format:
    runs-on: windows-latest

    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Check out code
        uses: actions/checkout@v3

      - name: Run dotnet format
        run: dotnet format src/PepeProject.sln --verify-no-changes --verbosity detailed